# Generated by Django 3.2.5 on 2021-07-15 03:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=255)),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None)),
                ('country', models.CharField(max_length=255)),
                ('numberOfPages', models.IntegerField(default=0)),
                ('publisher', models.CharField(max_length=255)),
                ('released', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
